# Generated by Django 4.1 on 2023-08-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='owner',
            new_name='user',
        ),
    ]
